SELECT DISTINCT (MO.OID) ,MO.EID,MO.QUANTITY,SU.CONVEYANCE_TYPE
FROM MY_ORDER MO,PURCHASE_MANAGER PM, SUPPLY SU, EMPLOYEE EMP
WHERE MO.EID=PM.EID
      AND SU.OID=MO.OID
      AND EMP.EID=MO.EID
      AND MO.QUANTITY > 9 AND MO.QUANTITY < 21
      AND (SU.CONVEYANCE_TYPE = '5' OR SU.CONVEYANCE_TYPE = '4' OR SU.CONVEYANCE_TYPE = '3')  
ORDER BY QUANTITY
